# fly.toml app configuration file generated for elfood on 2023-05-07T18:51:44+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "elfood"
primary_region = "arn"

[build]
#  builder = "paketobuildpacks/builder:base"
  builder = "heroku/buildpacks:20"

[command]
  start = "node app.mjs"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
